[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ipyleaflet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipyleaflet = ">=0.19.2,<0.20"
pandas = ">=2.2.3,<3"
ipywidgets = ">=8.1.5,<9"
jupyter = ">=1.1.1,<2"
