---
title: "Maplibre"
format: html
---

Setting up map

<script src='https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.js'></script>
<link href='https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.css' rel='stylesheet' />

<div id='map' style='width: 400px; height: 300px;'></div>
<script>
// Define the map syle (OpenStreetMap raster tiles)
const style = {
  "version": 8,
  "name": "Positron",
  "metadata": {
    "mapbox:autocomposite": false,
    "mapbox:groups": {
      "101da9f13b64a08fa4b6ac1168e89e5f": {
        "collapsed": false,
        "name": "Places"
      },
      "a14c9607bc7954ba1df7205bf660433f": {"name": "Boundaries"},
      "b6371a3f2f5a9932464fa3867530a2e5": {
        "collapsed": false,
        "name": "Transportation"
      }
    },
    "mapbox:type": "template",
    "openmaptiles:mapbox:owner": "openmaptiles",
    "openmaptiles:mapbox:source:url": "mapbox://openmaptiles.4qljc88t",
    "openmaptiles:version": "3.x",
    "maputnik:renderer": "mlgljs"
  },
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "https://api.maptiler.com/tiles/v3-openmaptiles/tiles.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL"
    }
  },
  "sprite": "https://openmaptiles.github.io/positron-gl-style/sprite",
  "glyphs": "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=get_your_own_OpIi9ZULNHzrESv6T2vL",
  "layers": [
    {
      "id": "background",
      "type": "background",
      "filter": ["all"],
      "paint": {"background-color": "rgb(242,243,240)"}
    },
    {
      "id": "park",
      "type": "fill",
      "source": "openmaptiles",
      "source-layer": "park",
      "filter": ["==", "$type", "Polygon"],
      "layout": {"visibility": "visible"},
      "paint": {
        "fill-color": "rgba(131, 168, 117, 0.3)",
        "fill-outline-color": "rgba(103, 135, 103, 1)"
      }
    },
    {
      "id": "water",
      "type": "fill",
      "source": "openmaptiles",
      "source-layer": "water",
      "filter": [
        "all",
        ["==", "$type", "Polygon"],
        ["!=", "brunnel", "tunnel"]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"fill-antialias": true, "fill-color": "rgb(194, 200, 202)"}
    },
    {
      "id": "landuse_residential",
      "type": "fill",
      "source": "openmaptiles",
      "source-layer": "landuse",
      "maxzoom": 16,
      "filter": [
        "all",
        ["==", "$type", "Polygon"],
        ["==", "class", "residential"]
      ],
      "layout": {"visibility": "visible"},
      "paint": {
        "fill-color": "rgba(226, 226, 182, 0.65)",
        "fill-opacity": {"base": 0.6, "stops": [[8, 0.8], [9, 0.6]]}
      }
    },
    {
      "id": "landcover_wood",
      "type": "fill",
      "source": "openmaptiles",
      "source-layer": "landcover",
      "minzoom": 10,
      "filter": ["all", ["==", "$type", "Polygon"], ["==", "class", "wood"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "fill-color": "rgba(33, 59, 33, 0.44)",
        "fill-opacity": {"base": 1, "stops": [[8, 0], [12, 1]]}
      }
    }
  ],
};

// Initialise the map
const map = new maplibregl.Map({
  container: 'map',
  style: style,
  center: [-1.54, 53.801], // starting position [lng, lat]
  zoom: 10
});

// Add the navigation control
map.addControl(new maplibregl.NavigationControl());
</script>

