[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bokeh"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bokeh = ">=3.7.2,<4"
pandas = ">=2.2.3,<3"
