[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "voila_voici"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
dash = ">=3.0.2,<4"
plotly = ">=6.0.1,<7"
pandas = ">=2.2.3,<3"
jupyter = ">=1.1.1,<2"
voici = ">=0.8.0,<0.9"
