[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "folium_leaflet_filtering"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
folium = ">=0.19.5,<0.20"
geopandas = ">=1.0.1,<1.1"
matplotlib = ">=3.10.1,<3.11"
numpy = ">=2.2.4,<2.3"
jupyter = ">=1.1.1,<2"
itables = ">=2.3.0,<3"
